version: '3.8'

services:
  super-tic-tac-toe-api:
    container_name: supertictactoeapi
    build: ./
    image: stttapi
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
